#!/bin/bash
. /etc/profile.d/CP.sh
[[ -f /etc/profile.d/mdpsenv.sh ]] && . /etc/profile.d/mdpsenv.sh
[[ -f /etc/profile.d/vsenv.sh ]] && . /etc/profile.d/vsenv.sh

tmpfile=$(mktemp)

function IsVSX() {
  if [[ $(cpprod_util FwIsVSX | tr -d ' ') == "1" ]]; then
    return 0
  else
    return 1
  fi
}

if IsVSX; then
  echo "set virtual-system $INSTANCE_VSID" > $tmpfile
  echo "show ip-reachability-detection" >> $tmpfile
  clish -f $tmpfile
else
  clish -c "show ip-reachability-detection"
fi

rm -f $tmpfile >/dev/null 2>&1
