#!/bin/bash
echo -e "VSID\tName"
echo -e "0\t$(cat /opt/CPsuite-R80*/fw1/conf/vsname)" | grep -i "$1"
for v in /opt/CPsuite-R80*/fw1/CTX/CTX*/conf/vsname; do
  if [[ $v =~ '.*\/CTX([0-9]{5})\/.*' ]]; then
    ctxnum=$(echo ${BASH_REMATCH[1]##+(0)} | sed 's/^0*//')
    ctxname=$(cat $v)
    echo -e "$ctxnum\t$ctxname" | grep -i "$1"
  fi
done
